### PR TITLE
Refactor rewards asset index

### LINKED ISSUE #827: Move from `_getAssetIndex` to `rewardsController.getAssetIndex()`?
This is what is used here: https://github.com/bgd-labs/static-a-token-v3/blob/40d1a870c95e9a550f47d422d91a76ce43b55263/src/StaticATokenLM.sol#L277-L283

But I'm not sure that this is what we should do

### PR DESCRIPTION
**Pull request by Rubilmax**
# Pull Request

## Issue(s) fixed

This pull request:

- fixes #827 
- replaces #832 
- fixes https://github.com/spearbit-audits/review-morpho-june/issues/6

### CODE REVIEW

**Review by Rubilmax — COMMENTED** [review]
It looks like a pure optimization (both for the contract size as well as the runtime cost). So it'd be classified as informational. Accepting it goes against what we've said.

**Review by makcandrov — COMMENTED** [review]
`scaledTotalSupply` can be removed from `UserAssetBalance `

(ie delete [this line](https://github.com/morpho-org/morpho-aave-v3/blob/9dcd014ecf44855bbc1fa215bd36cc053b002a50/src/RewardsManager.sol#L412), [this line](https://github.com/morpho-org/morpho-aave-v3/blob/9dcd014ecf44855bbc1fa215bd36cc053b002a50/src/interfaces/IRewardsManager.sol#L10) and [this line](https://github.com/morpho-org/morpho-aave-v3/blob/9dcd014ecf44855bbc1fa215bd36cc053b002a50/src/RewardsManager.sol#L7))

(I don't know how to do suggestions on untouched parts of the code)

**Review by MerlinEgalite — COMMENTED** [review]
Last commit looks good but we lose the getter. We can still query on Aave's contract but I need to think about it

**Comment by MerlinEgalite** [comment]
In fact, it does not solve the issue raised by @QGarchery are you aware of that? Or perhaps I'm missing something

**Comment by Rubilmax** [comment]
> In fact, it does not solve the issue raised by @QGarchery are you aware of that? Or perhaps I'm missing something

Yes, that's what I told you in DM. But you wanted me to work on it, so I did. Also, I warned above:

> It looks like a pure optimization (both for the contract size as well as the runtime cost). So it'd be classified as informational. Accepting it goes against what we've said.

**Comment by MerlinEgalite** [comment]
> > In fact, it does not solve the issue raised by @QGarchery are you aware of that? Or perhaps I'm missing something
> 
> Yes, that's what I told you in DM. But you wanted me to work on it, so I did. Also, I warned above:
> 
> > It looks like a pure optimization (both for the contract size as well as the runtime cost). So it'd be classified as informational. Accepting it goes against what we've said.

Ok I didn't see your message

**Comment by MerlinEgalite** [comment]
I think we can close this

**Pull request closed without merging**
