### PR TITLE
Fix readme implementation addresses

### PR DESCRIPTION
**Pull request by makcandrov**

### CODE REVIEW

**Review by Rubilmax — APPROVED** [review]
I don't think it's a good practice to keep implementation addresses in the README

**Comment by MerlinEgalite** [comment]
> I don't think it's a good practice to keep implementation addresses in the README

Can you share the reasoning please?

**Review by MerlinEgalite — APPROVED** [review]

**Comment by Rubilmax** [comment]
> > I don't think it's a good practice to keep implementation addresses in the README
> 
> Can you share the reasoning please?

updated

**Review by MathisGD — COMMENTED** [review]
These address can change, thus not be accurate, but they can all be retrieved from the proxy's one (that will not change). Isn't it easier to just remove them from the README ?

**Review by pakim249CAL — APPROVED** [review]
I agree with romain and mathis, but im still approving because this is less wrong than before.

**Comment by makcandrov** [comment]
forgot to sign th ecommit 😅

**Pull request merged**
